[phases.setup]
packageManager = "npm"

[phases.install]
command = "npm install --omit=dev --legacy-peer-deps"

[phases.build]
command = "NODE_OPTIONS=\"--max_old_space_size=4096\" NEXT_TELEMETRY_DISABLED=1 npm run build:docker"

[start]
command = "npm run start"

# Variables de entorno adicionales
[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Configuraciones del sistema
[system]
packages = ["nodejs", "npm"]

