[phases.setup]
packageManager = "npm"

[phases.install]
command = "npm install --production"

[phases.build]
command = "npx prisma generate"

[start]
command = "npm start"

[variables]
NODE_ENV = "production"
