[phases.setup]
packageManager = "npm"

[phases.install]
command = "npm install --production"

[phases.build]
command = "npm run build"

[start]
command = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
